"""Load the 12 supplied source workbooks into a validated SQLite database."""
import sqlite3, shutil
from pathlib import Path
import pandas as pd
from src.common import *

TABLE_SPECS={
 'companies':('companies.xlsx','companies',False), 'profitandloss':('profitandloss.xlsx','profitandloss',True),
 'balancesheet':('balancesheet.xlsx','balancesheet',True), 'cashflow':('cashflow.xlsx','cashflow',True),
 'documents':('documents.xlsx','documents',False), 'analysis':('analysis.xlsx','analysis',False),
 'prosandcons':('prosandcons.xlsx','prosandcons',False), 'sectors':('sectors.xlsx','sectors',False), 'stock_prices':('stock_prices.xlsx','stock_prices',False), 'peer_groups':('peer_groups.xlsx','peer_groups',False)
}

def load():
    """Create a fresh database and load all core and supplementary source files."""
    if DB_PATH.exists(): DB_PATH.unlink()
    schema=(ROOT/'src/etl/schema.sql').read_text(encoding='utf-8')
    conn=sqlite3.connect(DB_PATH); conn.executescript(schema); conn.execute('PRAGMA foreign_keys=ON')
    audits=[]
    # companies first
    c=read_excel_clean(SOURCE_DIR/'companies.xlsx'); c=c.rename(columns={'id':'source_id'}); c['company_id']=c['company_name'].map(lambda x:'') if 'company_id' not in c else c['company_id'].map(norm_ticker)
    # companies source uses id as ticker
    if 'company_id' not in c or c['company_id'].eq('').all(): c['company_id']=c['source_id'].map(norm_ticker)
    cols=['company_id','company_name','company_logo','chart_link','about_company','website','nse_profile','bse_profile','face_value','book_value','roce_percentage','roe_percentage']
    for col in cols:
        if col not in c: c[col]=None
    c=c[cols].drop_duplicates('company_id',keep='first')
    c.to_sql('companies',conn,if_exists='append',index=False); audits.append({'table':'companies','source_rows':len(c),'loaded_rows':len(c),'rejected_rows':0,'severity':''})
    for table,(fname,_,has_year) in TABLE_SPECS.items():
        if table=='companies': continue
        df=read_excel_clean(SOURCE_DIR/fname)
        if 'company_id' in df: df['company_id']=df['company_id'].map(norm_ticker)
        if 'year' in df: df['year']=df['year'].map(norm_year)
        if table=='documents': df=df.rename(columns={'year':'year','annual_report':'annual_report'})
        if table=='peer_groups':
            df.columns=['id','peer_group_name','company_id','is_benchmark']; df['company_id']=df.company_id.map(norm_ticker); df['is_benchmark']=df.is_benchmark.astype(str).str.lower().eq('true').astype(int); df=df[['peer_group_name','company_id','is_benchmark']].drop_duplicates(['peer_group_name','company_id'])
        if table=='analysis':
            rows=[]
            import re
            for _,r0 in df.iterrows():
                for metric in ['compounded_sales_growth','compounded_profit_growth','stock_price_cagr','roe']:
                    txt=str(r0.get(metric,'')); m=re.search(r'(\d+)\s*Years?:?\s*([\d.]+)%',txt)
                    if m: rows.append((norm_ticker(r0['company_id']),metric,int(m.group(1)),float(m.group(2))))
            df=pd.DataFrame(rows,columns=['company_id','metric_type','period_years','value_pct']).drop_duplicates(['company_id','metric_type','period_years'])
        if table in {'profitandloss','balancesheet','cashflow'}: df=dedupe_company_year(df,table,audits)
        # keep only columns represented by target schema
        target_cols=pd.read_sql_query(f'PRAGMA table_info({table})',conn)['name'].tolist()
        for col in target_cols:
            if col not in df: df[col]=None
        df=df[target_cols]
        if table=='documents': df['year']=pd.to_numeric(df['year'],errors='coerce').astype('Int64')
        if table=='stock_prices': df['date']=pd.to_datetime(df['date'],errors='coerce').dt.strftime('%Y-%m-%d')
        if table=='prosandcons':
            df=df[df.company_id.isin(c.company_id)]
        if 'company_id' in df.columns: df=df[df.company_id.isin(c.company_id)]
        if table=='stock_prices': df=df.drop_duplicates(['company_id','date'])
        df.to_sql(table,conn,if_exists='append',index=False)
        if not any(a['table']==table for a in audits): audits.append({'table':table,'source_rows':len(df),'loaded_rows':len(df),'rejected_rows':0,'severity':''})
    # supplied financial_ratios is retained as a source input; computed table is generated by ratio engine.
    pd.DataFrame(audits).to_csv(OUTPUT_DIR/'load_audit.csv',index=False)
    conn.commit(); conn.close()
    return DB_PATH

if __name__=='__main__': print(load())
